const data=[{name:'Banca Ifis',ticker:'IF.MI',price:'€15,82',pe:'7,4x',fair:'€21,50',upside:'+35,9%',score:68,signal:'Watch'},{name:'Unipol',ticker:'UNI.MI',price:'€13,84',pe:'8,1x',fair:'€17,20',upside:'+24,3%',score:79,signal:'Interessante'},{name:'Microsoft',ticker:'MSFT',price:'$510,20',pe:'35,2x',fair:'$545',upside:'+6,8%',score:88,signal:'Hold'},{name:'Amazon',ticker:'AMZN',price:'$226,40',pe:'32,5x',fair:'$260',upside:'+14,8%',score:86,signal:'Hold'},{name:'Meta Platforms',ticker:'META',price:'$778',pe:'25,8x',fair:'$860',upside:'+10,5%',score:84,signal:'Watch'}];
const views=[...document.querySelectorAll('.view')];
function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const titles={dashboard:'Dashboard',watchlist:'Watchlist',portfolio:'Portafoglio',analysis:'Analisi titolo',alerts:'Alert'};document.getElementById('page-title').textContent=titles[id]||'Dashboard';window.scrollTo(0,0)}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
document.getElementById('refresh').onclick=()=>{document.getElementById('time').textContent=new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})};
document.getElementById('time').textContent=new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});
document.getElementById('signals').innerHTML=data.slice(0,4).map(x=>'<div class="signal"><div class="signal-title"><span class="signal-icon">'+x.ticker.slice(0,2)+'</span><div><b>'+x.name+'</b><small>'+x.ticker+' · P/E '+x.pe+'</small></div></div><div class="signal-right"><b class="'+(x.signal==='Interessante'?'up':'')+'">'+x.upside+'</b><small>'+x.signal+'</small></div></div>').join('');
document.getElementById('watch-table').innerHTML=data.map(x=>'<tr><td><b>'+x.name+'</b><small> '+x.ticker+'</small></td><td>'+x.price+'</td><td>'+x.pe+'</td><td>'+x.fair+'</td><td class="up">'+x.upside+'</td><td><b>'+x.score+'</b>/100</td><td><span class="badge '+(x.signal==='Interessante'?'green':'amber')+'">'+x.signal+'</span></td></tr>').join('');
document.getElementById('search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();if(!q)return;const found=data.find(x=>(x.name+' '+x.ticker).toLowerCase().includes(q));if(found)showView('analysis')});